[package]
name = "from_variants"
version = "0.1.1-pre"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/from_variants"
documentation = "https://docs.rs/from_variants/0.1.0"
license = "MIT/Apache-2.0"
categories = ["development-tools", "rust-patterns"]
description = "Rust macro to automatically generate conversions for newtype enums."
readme = "README.md"

[badges]
travis-ci = { repository = "TedDriggs/from_variants" }

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"

[dependencies.error-chain]
version = "0.10"
default-features = false