[package]
name = "from_variants"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"

[dependencies.error-chain]
version = "0.10"
default-features = false