[package]
name = "from_variants_impl"
version = "0.4.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/from_variants"
documentation = "https://docs.rs/from_variants/0.4.0"
license = "MIT/Apache-2.0"
description = "Internal helper crate for from_variants crate."
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.5.0"
quote = "0.5.2"
syn = "0.13.10"

[dependencies.error-chain]
version = "0.11.0"
default-features = false

[dev-dependencies]
pretty_assertions = "0.1"
