[package]
name = "from_variants_impl"
version = "0.2.4"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/from_variants"
documentation = "https://docs.rs/from_variants/0.2.4"
license = "MIT/Apache-2.0"
description = "Internal helper crate for from_variants crate."

[lib]
proc-macro = true

[dependencies]
darling = "0.3.0"
syn = "0.12.10"
quote = "0.4.0"

[dependencies.error-chain]
version = "0.10"
default-features = false

[dev-dependencies]
pretty_assertions = "0.1"